apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - seldon-deployment-example.json

patches:
  - path: ../overlays/hpa-spec.json
    target:
      group: machinelearning.seldon.io
      version: v1
      kind: SeldonDeployment
