---
# Source: seldon-model-server/templates/model-server-seldon-deployment.yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model-server
spec:
  name: seldon-model-server
  predictors:
    - name: default
      graph:
        name: default
        implementation: SKLEARN_SERVER
        children: []
        modelUri: gs://news_classifier/model
        parameters:
          - name: method
            type: STRING
            value: predict
      componentSpecs:
        - spec:
            containers:
              - name: default
                env:
                  - name: SELDON_LOG_LEVEL
                    value: "DEBUG"
            terminationGracePeriodSeconds: 1
      replicas: 1
      engineResources: {}
      svcOrchSpec: {}
      traffic: 100
      explainer:
        containerSpec:
          name: ""
          resources: {}
  annotations:
    seldon.io/engine-seldon-log-messages-externally: "true"
