apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - seldon-deployment-example/seldon-deployment-example.json
  - seldon-deployment-example-2/seldon-deployment-example-2.json
  - seldon-deployment-example-3/seldon-deployment-example-3.json
  - xss-example/xss-example.json

patches:
  - path: overlays/hpa-spec.json
    target:
      group: machinelearning.seldon.io
      version: v1
      kind: SeldonDeployment
